Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      ArtifactRelation:
        m-mj7bq9tt5n3u9rdvuv6w:
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
      SupplierTemplateConfigs:
        - Name: 模板1
          Url: ros_templates/template1.yaml
          PredefinedParameters: []
    TemplateConfigs:
      - Name: 模板1
        Url: ros_templates/template1.yaml
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      模板1:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Active Directory 域服务 (AD DS) 提供用于存储目录数据并使此数据可供网络用户和管理员使用的方法。 例如，AD DS 存储有关用户帐户的信息，例如名称、密码、电话号码等。 AD DS 还为同一网络上的授权用户提供了访问此信息的方法。
    Image: resources/icons/service_logo.png
    Name: 'Windows Active Directory 域服务快速部署 '
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: EcsImage
    ArtifactName: activedirectory
    Description: activedirectory
    ArtifactProperty:
      ImageId: m-mj7a56zk6xp8ji7j083e
      RegionId: ap-northeast-2
